import { resolve } from "path";

import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": resolve(__dirname, "./src"),
    },
  },
  test: {
    testTimeout: 15000, // UI integration tests with form navigation need extra time under coverage instrumentation
    environment: "jsdom",
    include: ["tests/**/*.test.{ts,tsx}"],
    setupFiles: ["tests/setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      reportsDirectory: "./coverage",
      include: [
        "src/lib/**",
        "src/services/**",
        "src/hooks/**",
        "src/middleware.ts",
        "src/components/layout/AdminSidebar.tsx",
        "src/components/layout/ResidentSidebar.tsx",
        "src/components/layout/Header.tsx",
        "src/components/features/**",
        "src/components/ui/StatusBadge.tsx",
        "src/app/(auth)/**",
        "src/app/r/**",
        "src/app/api/v1/auth/me/**",
        "src/app/api/v1/residents/me/**",
        "src/app/api/v1/residents/**/id-proof/**",
        "src/app/api/v1/residents/**/ownership-proof/**",
        "src/app/api/v1/super-admin/plans/**",
        "src/app/api/v1/super-admin/discounts/**",
        "src/app/api/v1/societies/[id]/admins/**",
        "src/app/api/v1/residents/[id]/send-setup-email/**",
        "src/app/api/v1/residents/route.ts",
        "src/app/api/v1/residents/[id]/approve/**",
        "src/app/api/v1/residents/[id]/reject/**",
        "src/app/api/v1/residents/[id]/send-verification/**",
        "src/app/api/v1/residents/bulk-upload/**",
        "src/app/api/v1/auth/forgot-password/**",
        "src/app/api/v1/auth/login/**",
        "src/app/api/v1/auth/register-society/**",
        "src/app/api/v1/auth/plans/**",
        "src/app/api/v1/societies/[id]/migration/import-stream/**",
        "src/lib/migration-processor.ts",
        "src/app/api/v1/societies/[id]/fees/[feeId]/payments/**",
        "src/app/api/cron/fee-status-activate/**",
        "src/app/api/cron/fee-overdue-check/**",
        "src/app/api/v1/societies/[id]/events/**",
        "src/app/api/v1/residents/me/events/**",
        "src/app/api/v1/societies/[id]/petitions/**",
        "src/app/api/v1/residents/me/petitions/**",
        "src/app/api/v1/super-admin/notifications/**",
        "src/app/api/v1/super-admin/societies/[id]/suspend/**",
        "src/app/api/v1/super-admin/societies/[id]/reactivate/**",
        "src/app/api/v1/super-admin/societies/[id]/offboard/**",
        "src/app/api/v1/super-admin/societies/[id]/status-history/**",
        "src/app/api/v1/super-admin/societies/[id]/residents/**",
        "src/app/api/v1/super-admin/societies/[id]/fees/**",
        "src/app/api/v1/super-admin/societies/[id]/expenses/**",
        "src/app/api/v1/super-admin/societies/[id]/events/**",
        "src/app/api/v1/super-admin/societies/[id]/petitions/**",
        "src/app/api/v1/super-admin/societies/[id]/broadcasts/**",
        "src/app/api/v1/super-admin/societies/[id]/governing-body/**",
        "src/app/api/v1/super-admin/societies/[id]/migrations/**",
        "src/app/api/v1/super-admin/societies/[id]/settings/**",
        "src/app/api/v1/super-admin/societies/[id]/reports/**",
        "src/app/api/v1/super-admin/residents/**",
        "src/app/api/v1/super-admin/operations/**",
        "src/app/api/v1/super-admin/search/**",
        "src/app/api/v1/super-admin/announcements/**",
        "src/app/api/v1/super-admin/support/**",
        "src/app/api/v1/admin/announcements/**",
        "src/app/api/v1/admin/support/**",
        "src/app/api/cron/support-auto-close/**",
        "src/app/api/v1/societies/[id]/payment-setup/**",
        "src/app/api/v1/societies/[id]/payment-claims/**",
        "src/app/api/v1/residents/me/payment-claims/**",
        "src/app/api/v1/super-admin/platform-payment-setup/**",
        "src/app/api/v1/super-admin/subscription-payment-claims/**",
        "src/app/api/v1/societies/[id]/subscription-payment-claims/**",
        "src/components/layout/SuperAdminSidebar.tsx",
        "src/app/admin/fees/claims/page.tsx",
        "src/app/api/cron/payment-claim-reminders/**",
        "src/app/api/v1/config/payment-features/**",
        "src/app/api/v1/societies/[id]/platform-payment-info/**",
        "src/app/admin/settings/subscription/page.tsx",
        "src/app/admin/residents/page.tsx",
        "src/app/api/v1/residents/me/support/**",
        "src/app/api/v1/admin/resident-support/**",
      ],
      exclude: [
        "src/lib/prisma.ts",
        "src/lib/supabase/**",
        "src/lib/whatsapp.ts",
        "src/lib/email-templates/**",
        "src/app/r/loading.tsx",
        "src/app/api/v1/societies/[id]/migration/import-stream/**",
      ],
      thresholds: {
        lines: 95,
        functions: 95,
        branches: 95,
        statements: 95,
      },
    },
  },
});
